### Ping
GET http://localhost:8080/ping
Content-Type: application/json

### Payment
POST http://localhost:8080/v1/payments
Content-Type: application/json

{

}


### Payment Malformed
POST http://localhost:8080/v1/payments
Content-Type: application/json

{
    "json": ""malformed",
}