services:
  api-gateway:
    image: krakend:2.9
    container_name: api_gateway
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: ["run", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - payment-service
      - otel-collector
    networks:
      - payment_network
  floci:
    container_name: floci_aws_emulator
    image: floci/floci:latest
    ports:
      - "4566:4566"
    environment:
      - FLOCI_HOSTNAME=floci
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_floci/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - payment_network

  sqs-init:
    image: amazon/aws-cli:latest
    container_name: sqs_init
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh
    command: >
      -c "
      echo 'Esperando a que Floci responda...';
      until aws --endpoint-url=http://floci:4566 sqs list-queues > /dev/null 2>&1; do
        sleep 1;
      done;
      echo 'Floci listo. Creando cola payments-queue...';
      aws --endpoint-url=http://floci:4566 sqs create-queue --queue-name payments-queue;
      echo 'Cola creada exitosamente.';
      "
    depends_on:
      floci:
        condition: service_healthy
    networks:
      - payment_network

  payment-service:
    build:
      context: .
      dockerfile: build/payments_ingestor/Dockerfile
    container_name: payments_ingestor
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - REDIS_ADDR=redis:6379
      - OTEL_COLLECTOR_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=payments_ingestor
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      floci:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - payment_network

  outbox-relayer:
    build:
      context: .
      dockerfile: ./build/outbox_relayer/Dockerfile
    container_name: outbox_relayer
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - BATCH_SIZE=100
      - POLL_INTERVAL_MS=1000
      - AWS_REGION=us-east-1
      - SQS_ENDPOINT=http://floci:4566
      - SQS_QUEUE_URL=http://floci:4566/000000000000/payments-queue
      - SQS_QUEUE_NAME=payments-queue
      - OTEL_COLLECTOR_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=outbox_relayer
    depends_on:
      postgres:
        condition: service_healthy
      floci:
        condition: service_healthy
      sqs-init:
        condition: service_completed_successfully
    networks:
      - payment_network
  
  events-consumer:
    build:
      context: .
      dockerfile: ./build/events_consumer/Dockerfile # Ajusta la ruta a tu Dockerfile
    container_name: events_consumer
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - SQS_REGION=us-east-1
      - SQS_ENDPOINT=http://floci:4566
      - SQS_QUEUE_URL=http://floci:4566/000000000000/payments-queue
      - OTEL_COLLECTOR_ADDR=otel-collector:4317
      - OTEL_SERVICE_NAME=events_consumer
    depends_on:
      postgres:
        condition: service_healthy
      floci:
        condition: service_healthy
      sqs-init:
        condition: service_completed_successfully # Espera a que la cola se cree automáticamente
    networks:
      - payment_network

  redis:
    image: redis:7-alpine
    container_name: payment_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel notice
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - payment_network

  postgres:
    image: postgres:16-alpine
    container_name: payment_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - payment_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317" # Recibe trazas de KrakenD y Go
      - "8889:8889" # Exposes Prometheus metrics from spanmetrics connector
    depends_on:
      - tempo
    networks:
      - payment_network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
    networks:
      - payment_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
    volumes:
      - ./config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/grafana-dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/dashboard-provider.yaml
      - ./config/payment-dashboard.json:/var/lib/grafana/dashboards/payment-dashboard.json
    depends_on:
      - tempo
    networks:
      - payment_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - payment_network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      - payment_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - payment_network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - payment_network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - payment_network


volumes:
  redis_data:
  postgres_data:

networks:
  payment_network:
    driver: bridge